
flags = {
    'ZA': 'South Africa',
    'AL': 'Albania',
    'DZ': 'Algeria',
    'BH': 'Bahrain',
    'EG': 'Egypt',
    'IQ': 'Iraq',
    'JO': 'Jordan',
    'KW': 'Kuwait',
    'LB': 'Lebanon',
    'LY': 'Libya',
    'MA': 'Morocco',
    'OM': 'Oman',
    'QA': 'Qatar',
    'SA': 'Saudi Arabia',
    'SY': 'Syria',
    'TN': 'Tunisia',
    'AE': 'United Arab Emirates',
    'YE': 'Yemen',
    'AM': 'Armenia',
    'AZ': 'Azerbaijan',
    'ES': 'Spain',
    'BY': 'Belarus',
    'IN': 'India',
    'BA': 'Bosnia and Herzegovina',
    'BG': 'Bulgaria',
    'CN': 'China',
    'HK': 'Hong Kong SAR China',
    'MO': 'Macao SAR China',
    'SG': 'Singapore',
    'TW': 'Taiwan',
    'HR': 'Croatia',
    'CZ': 'Czech Republic',
    'DK': 'Denmark',
    'BE': 'Belgium',
    'NL': 'Netherlands',
    'AU': 'Australia',
    'BZ': 'Belize',
    'CA': 'Canada',
    'IE': 'Ireland',
    'JM': 'Jamaica',
    'NZ': 'New Zealand',
    'PH': 'Philippines',
    'ZA': 'South Africa',
    'TT': 'Trinidad and Tobago',
    'VI': 'U.S. Virgin Islands',
    'GB': 'United Kingdom',
    'US': 'United States',
    'ZW': 'Zimbabwe',
    'EE': 'Estonia',
    'FO': 'Faroe Islands',
    'FI': 'Finland',
    'FR': 'France',
    'LU': 'Luxembourg',
    'MC': 'Monaco',
    'CH': 'Switzerland',
    'GE': 'Georgia',
    'AT': 'Austria',
    'DE': 'Germany',
    'LI': 'Liechtenstein',
    'GR': 'Greece',
    'IL': 'Israel',
    'HU': 'Hungary',
    'IS': 'Iceland',
    'ID': 'Indonesia',
    'IT': 'Italy',
    'JP': 'Japan',
    'KZ': 'Kazakhstan',
    'KR': 'South Korea',
    'LV': 'Latvia',
    'LT': 'Lithuania',
    'MK': 'Macedonia',
    'BN': 'Brunei',
    'MY': 'Malaysia',
    'MT': 'Malta',
    'MN': 'Mongolia',
    'NO': 'Norway',
    'IR': 'Iran',
    'PL': 'Poland',
    'BR': 'Brazil',
    'PT': 'Portugal',
    'RO': 'Romania',
    'RU': 'Russia',
    'SK': 'Slovakia',
    'SI': 'Slovenia',
    'AR': 'Argentina',
    'BO': 'Bolivia',
    'CL': 'Chile',
    'CO': 'Colombia',
    'CR': 'Costa Rica',
    'DO': 'Dominican Republic',
    'EC': 'Ecuador',
    'SV': 'El Salvador',
    'GT': 'Guatemala',
    'HN': 'Honduras',
    'MX': 'Mexico',
    'NI': 'Nicaragua',
    'PA': 'Panama',
    'PY': 'Paraguay',
    'PE': 'Peru',
    'PR': 'Puerto Rico',
    'UY': 'Uruguay',
    'VE': 'Venezuela',
    'KE': 'Kenya',
    'SE': 'Sweden',
    'SY': 'Syria',
    'TH': 'Thailand',
    'TR': 'Turkey',
    'UA': 'Ukraine',
    'UZ': 'Uzbekistan',
    'VN': 'Vietnam',
    'CY': 'United Kingdom',
    'XH': 'South Africa',
    'ZU': 'South Africa'
}
